// <auto-generated />
using System;
using IncidentCreator.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IncidentCreator.Data.Migrations
{
    [DbContext(typeof(IncidentCreatorDbContext))]
    [Migration("20210604054938_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IncidentCreator.Data.Models.Incident", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("IncidentCreator.Data.Models.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsUnderIncident")
                        .HasColumnType("bit")
                        .HasColumnName("is_under_incident");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<Guid?>("incident_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("incident_id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = new Guid("8770e553-7b59-41d7-8f57-5a8cfe510b1f"),
                            IsUnderIncident = false,
                            Name = "TestProduct-1"
                        },
                        new
                        {
                            ID = new Guid("c92f276a-5f2a-455b-9e34-af11cfd4c025"),
                            IsUnderIncident = false,
                            Name = "TestProduct-2"
                        },
                        new
                        {
                            ID = new Guid("6b6b4d3b-0ff1-4002-8236-d24aa3c6fd98"),
                            IsUnderIncident = false,
                            Name = "TestProduct-3"
                        });
                });

            modelBuilder.Entity("IncidentCreator.Data.Models.Product", b =>
                {
                    b.HasOne("IncidentCreator.Data.Models.Incident", "Incident")
                        .WithMany("Products")
                        .HasForeignKey("incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentCreator.Data.Models.Incident", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
